[project]
name = "desarrollo-proyecto-signalforhelp-entrenamiento"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mlflow>=3.4.0",
    "ultralytics>=8.3.201",
]
